### ISSUE TITLE
Tag vs version in package.json does not align

### ISSUE THREAD

**Issue by BPScott** [raulriera/probot-minimum-reviews#10]
Thanks for cutting a release tag. However it seems things get confused if the tag and version in package.json do not line up. Also the convention is to name release tags starting with a `v` rather than jumping straight into the number.

Can you tag `v1.0.6` to match the version number you have in [your package.json](https://github.com/raulriera/probot-minimum-reviews/blob/master/package.json#L3)

**Comment by raulriera** [comment]
Hey Scott, thanks for the info... You clearly know more JavaScript than me 🙂 I just gave you access got both repos so you don't need to create PRs or issues 🙂 thanks!

**Comment by BPScott** [comment]
Cheers
