### ISSUE TITLE
[Request] Attach a screenshot to show the bot in action

### ISSUE THREAD

**Issue by itaditya** [raulriera/probot-minimum-reviews#3]
It would be great to see a screenshot in the readme. I think this will increase the credibility of the bot

**Comment by raulriera** [comment]
Will do 🙂 I'm trying to properly setup the logo and stuff.. maybe I should just photoshop my face out of this screenshot and use it 🙂 

![danxmxxwsaamv94](https://user-images.githubusercontent.com/24159/38525647-16a2f6e0-3c21-11e8-8e64-1469d2c5fc42.jpg)

**Comment by raulriera** [comment]
Fixed :)
